name: Flutter web build

on:
  push:
    branches:
      - "main"

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'

      - name: build
        run: |
          flutter pub get
          flutter build web --web-renderer html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: ban.reef-gh-static.ree-jp.net
